import { v } from "convex/values"

import { mutation, query } from "./_generated/server"
import { pointInPolygon, polygonCentroid, boundingRadius } from "./lib/pointInPolygon"

export const list = query({
  args: {},
  handler: async (ctx) => {
    const clusters = await ctx.db.query("clusters").collect()
    const clustersWithCounts = await Promise.all(
      clusters.map(async (cluster) => {
        const leads = await ctx.db
          .query("leads")
          .withIndex("by_clusterId", (q) => q.eq("clusterId", cluster._id))
          .collect()
        return { ...cluster, leadCount: leads.length }
      })
    )
    return clustersWithCounts
  },
})

export const get = query({
  args: {
    clusterId: v.id("clusters"),
  },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.clusterId)
  },
})

export const getLeads = query({
  args: {
    clusterId: v.id("clusters"),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("leads")
      .withIndex("by_clusterId", (q) => q.eq("clusterId", args.clusterId))
      .collect()
  },
})

export const updateName = mutation({
  args: {
    clusterId: v.id("clusters"),
    name: v.string(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.clusterId, { name: args.name })
  },
})

export const update = mutation({
  args: {
    clusterId: v.id("clusters"),
    name: v.optional(v.string()),
    radiusKm: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const patch: Record<string, string | number> = {}
    if (args.name !== undefined) {
      patch.name = args.name
    }
    if (args.radiusKm !== undefined) {
      patch.radiusKm = args.radiusKm
    }
    if (Object.keys(patch).length > 0) {
      await ctx.db.patch(args.clusterId, patch)
    }
  },
})

export const deleteAllClusters = mutation({
  args: {},
  handler: async (ctx) => {
    const clusters = await ctx.db.query("clusters").collect()
    for (const cluster of clusters) {
      await ctx.db.delete(cluster._id)
    }

    const leads = await ctx.db.query("leads").collect()
    const now = Date.now()
    let leadsPatched = 0
    for (const lead of leads) {
      if (lead.clusterId !== undefined) {
        await ctx.db.patch(lead._id, { clusterId: undefined, updatedAt: now })
        leadsPatched++
      }
    }

    return { clustersDeleted: clusters.length, leadsPatched }
  },
})

export const deleteCluster = mutation({
  args: {
    clusterId: v.id("clusters"),
  },
  handler: async (ctx, args) => {
    const cluster = await ctx.db.get(args.clusterId)
    if (!cluster) {
      throw new Error("Cluster not found")
    }

    // Find all leads assigned to this cluster
    const leads = await ctx.db
      .query("leads")
      .withIndex("by_clusterId", (q) => q.eq("clusterId", args.clusterId))
      .collect()

    // Unassign each lead and log activity
    const now = Date.now()
    for (const lead of leads) {
      await ctx.db.patch(lead._id, {
        clusterId: undefined,
        updatedAt: now,
      })
      await ctx.db.insert("activities", {
        leadId: lead._id,
        type: "note_added",
        description: `Unassigned from cluster "${cluster.name}"`,
        metadata: {
          clusterId: args.clusterId,
          clusterName: cluster.name,
        },
        createdAt: now,
      })
    }

    // Delete the cluster doc
    await ctx.db.delete(args.clusterId)

    return { leadsUnassigned: leads.length }
  },
})

export const createPolygonCluster = mutation({
  args: {
    name: v.string(),
    boundary: v.array(v.object({ lat: v.number(), lng: v.number() })),
  },
  handler: async (ctx, args) => {
    const { name, boundary } = args

    // Compute centroid and bounding radius
    const centroid = polygonCentroid(boundary)
    const radius = boundingRadius(centroid, boundary)
    const radiusKm = Math.max(radius, 1)

    // Query all leads with coordinates
    const allLeads = await ctx.db.query("leads").collect()
    const leadsWithCoords = allLeads.filter(
      (l) => l.latitude !== undefined && l.longitude !== undefined
    )

    // Find leads enclosed by the polygon
    const enclosedLeads = leadsWithCoords.filter((l) =>
      pointInPolygon(
        { lat: l.latitude as number, lng: l.longitude as number },
        boundary
      )
    )

    // Create the cluster doc
    const clusterId = await ctx.db.insert("clusters", {
      name,
      boundary,
      centerLat: centroid.lat,
      centerLng: centroid.lng,
      radiusKm,
      leadCount: enclosedLeads.length,
      isAutoGenerated: false,
    })

    // Assign enclosed leads to the cluster and log activity
    const now = Date.now()
    for (const lead of enclosedLeads) {
      await ctx.db.patch(lead._id, {
        clusterId,
        updatedAt: now,
      })
      await ctx.db.insert("activities", {
        leadId: lead._id,
        type: "note_added",
        description: `Assigned to cluster "${name}"`,
        metadata: {
          clusterId,
          clusterName: name,
        },
        createdAt: now,
      })
    }

    return {
      clusterId,
      leadCount: enclosedLeads.length,
    }
  },
})
