"use client"

import { useState } from "react"
import { useAction, useQuery } from "convex/react"
import { Loader2, MapPin, Sparkles, Users } from "lucide-react"
import { api } from "../../../convex/_generated/api"
import type { Id } from "../../../convex/_generated/dataModel"

import { AppLayout } from "@/components/layout/app-layout"
import { ClusterDetail } from "@/components/clusters/cluster-detail"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

type Cluster = {
  _id: Id<"clusters">
  name: string
  centerLat: number
  centerLng: number
  radiusKm: number
  leadCount: number
  isAutoGenerated: boolean
}

export default function ClustersPage() {
  const clusters = useQuery(api.clusters.list) as Cluster[] | undefined
  const autoGenerate = useAction(api.clusters.autoGenerate)
  const [selectedClusterId, setSelectedClusterId] = useState<Id<"clusters"> | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [generateResult, setGenerateResult] = useState<string | null>(null)

  async function handleAutoGenerate() {
    setIsGenerating(true)
    setGenerateResult(null)
    setSelectedClusterId(null)
    try {
      const result = await autoGenerate()
      setGenerateResult(
        `Created ${result.clustersCreated} clusters, assigned ${result.leadsAssigned} leads`
      )
    } catch {
      setGenerateResult("Failed to generate clusters")
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <AppLayout>
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <h2 className="text-xl font-semibold tracking-tight">Clusters</h2>
            <p className="text-muted-foreground text-sm">
              Group leads by geographic proximity for targeted outreach.
            </p>
          </div>
          <div className="flex items-center gap-3">
            {generateResult && (
              <p className="text-sm text-muted-foreground">{generateResult}</p>
            )}
            <Button onClick={handleAutoGenerate} disabled={isGenerating}>
              {isGenerating ? (
                <Loader2 className="size-4 animate-spin" />
              ) : (
                <Sparkles className="size-4" />
              )}
              {isGenerating ? "Generating..." : "Auto-generate Clusters"}
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-[340px_1fr]">
          {/* Left column: Cluster list */}
          <div className="space-y-3">
            {clusters === undefined ? (
              <div className="flex items-center justify-center py-12">
                <p className="text-muted-foreground">Loading clusters...</p>
              </div>
            ) : clusters.length === 0 ? (
              <Card>
                <CardContent className="p-4 pt-0">
                  <p className="text-muted-foreground text-sm py-8 text-center">
                    No clusters yet. Use &quot;Auto-generate Clusters&quot; to create clusters from your leads.
                  </p>
                </CardContent>
              </Card>
            ) : (
              clusters.map((cluster) => (
                <Card
                  key={cluster._id}
                  role="button"
                  tabIndex={0}
                  className={`cursor-pointer transition-colors hover:border-primary/50 ${
                    selectedClusterId === cluster._id ? "border-primary" : ""
                  }`}
                  onClick={() => setSelectedClusterId(cluster._id)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.preventDefault()
                      setSelectedClusterId(cluster._id)
                    }
                  }}
                >
                  <CardHeader className="p-4">
                    <div className="flex items-start justify-between">
                      <CardTitle>{cluster.name}</CardTitle>
                      {cluster.isAutoGenerated && (
                        <Badge variant="secondary">Auto</Badge>
                      )}
                    </div>
                    <CardDescription className="flex items-center gap-3 pt-1">
                      <span className="inline-flex items-center gap-1">
                        <Users className="size-3" />
                        {cluster.leadCount} leads
                      </span>
                      <span className="inline-flex items-center gap-1">
                        <MapPin className="size-3" />
                        {cluster.radiusKm} km
                      </span>
                    </CardDescription>
                  </CardHeader>
                </Card>
              ))
            )}
          </div>

          {/* Right column: Detail view or instruction */}
          <div>
            {selectedClusterId ? (
              <Card>
                <CardContent className="p-6">
                  <ClusterDetail clusterId={selectedClusterId} />
                </CardContent>
              </Card>
            ) : (
              <Card>
                <CardContent className="p-6">
                  <div className="flex flex-col items-center justify-center py-16 text-center">
                    <MapPin className="size-10 text-muted-foreground/50 mb-3" />
                    <p className="text-muted-foreground font-medium">Select a cluster</p>
                    <p className="text-muted-foreground text-sm mt-1">
                      Choose a cluster from the list to view its details and leads.
                    </p>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </section>
    </AppLayout>
  )
}
